### PR TITLE
`TestHandleHeartbeat2AA`  add test case

### LINKED ISSUE #191: should heartbeat RPC update commit?
`TestHandleHeartbeat2AA` expect commit would change.

but later I encounter a bug like this
- an old leader is separate away and receives a log(assume index 10) from a client(no chance to commit).
- while the majority elect a new leader and commit is up to index 15.
- when the old leader comes back to the cluster and receives a heartbeat RPC says commit is 15, it will apply the wrong log index 10(this log should be overwritten).

### PR DESCRIPTION
**Pull request by schneiderlin**
fix #191 

test 1: commit index and log term match, update committed
test 2: match but decrease, don't update
test 3: index 3's term not match, don't update 
test 4: committed index 3's term can be either 2 or 3, don't update

### CODE REVIEW

**Comment by Connor1996** [comment]
PTAL @NingLin-P

File: raft/raft_test.go [hunk 1]
```diff
@@ -589,8 +589,10 @@ func TestHandleHeartbeat2AA(t *testing.T) {
 		m       pb.Message
 		wCommit uint64
 	}{
-		{pb.Message{From: 2, To: 1, MsgType: pb.MessageType_MsgHeartbeat, Term: 2, Commit: commit + 1}, commit + 1},
-		{pb.Message{From: 2, To: 1, MsgType: pb.MessageType_MsgHeartbeat, Term: 2, Commit: commit - 1}, commit}, // do not decrease commit
+		{pb.Message{From: 2, To: 1, MsgType: pb.MessageType_MsgHeartbeat, Term: 2, LogTerm: 3, Commit: commit + 1}, commit + 1},
```
Comment (NingLin-P) [inline raft/raft_test.go]:
```suggestion
		{pb.Message{From: 2, To: 1, MsgType: pb.MessageType_MsgHeartbeat, Term: 3, LogTerm: 3, Commit: commit + 1}, commit + 1},
```
Leader's term should be greater or equal to `LogTerm`

File: raft/raft_test.go [hunk 2]
```diff
@@ -599,13 +601,13 @@ func TestHandleHeartbeat2AA(t *testing.T) {
 		sm := newTestRaft(1, []uint64{1, 2}, 5, 1, storage)
 		sm.becomeFollower(2, 2)
```
Comment (NingLin-P) [inline raft/raft_test.go]:
```suggestion
		sm.becomeFollower(3, 2)
```
Should be the last log's term.

**Comment by NingLin-P** [comment]
Sorry for the delay!
> test 4: committed index 3's term can be either 2 or 3, don't update

Do you mean we should not update to the committed index that greater than the last index?

**Comment by schneiderlin** [comment]
> test 4: committed index 3's term can be either 2 or 3, don't update

there are 2 parts.
1) can't set to 4: follower's last index is 3, so obviously can not set committed to 4
2) can't set to 3: the leader says the committed log is (index: 4, term: 3), given this information follower can only infer term of index 3 is <= 3. follower has to make sure term of index 3 is 3 before it sets committed to 3.

so follower's commit stays at 2

**Comment by schneiderlin** [comment]
please also take a look at `TestBcastBeat2AB`, it seems like heartbeat RPC's fields have different meanings.

### my understanding is as follows
a heartbeat RPC consists of
- MsgType
- To
- From
- Term, the term when the leader sends this RPC
- LogTerm, term of the commit log
- Commit, index of the commit log

a follower can use `LogTerm` and `Commit` to check `Log Matching` property and update committed accordingly.

### in TestBcastBeat2AB
https://github.com/pingcap-incubator/tinykv/blob/e01d729bd45cdf25f8c657a4dabf5229985007db/raft/raft_test.go#L942-L947
not sure it is prev index/term of which log

**Comment by NingLin-P** [comment]
`Index` and `LogTerm` fields in `Heartbeat` RPC are not strictly defined as `AppendEntries` and `RequestVote`, their meaning depends on how `Heartbeat` RPC implement.

**Comment by NingLin-P** [comment]
Actually, `TestBcastBeat2AB` is testing another approach to avoid the situation you mentioned at https://github.com/pingcap-incubator/tinykv/issues/191 by setting `m.Commit` to `min(raft.RaftLog.committed, raft.Prs[m.to].Match)`, because `Match` initialized to 0 and update by `AppendEntriesResp`, follower's log entry at `m.Commit` can be sure come from leader.

**Comment by NingLin-P** [comment]
Also, these two tests are too restricted to the implement, maybe we should delete them and add a more general test: simulating the network isolation and just checking how follower's commit index update, what do you think @schneiderlin ?

**Comment by schneiderlin** [comment]
good idea, I can work on that

File: raft/raft_test.go [hunk 3]
```diff
@@ -902,61 +869,55 @@ func TestDisruptiveFollower2AA(t *testing.T) {
...
-		2: min(sm.RaftLog.committed, sm.Prs[2].Match),
-		3: min(sm.RaftLog.committed, sm.Prs[3].Match),
+func TestHeartbeatUpdateCommit2AB(t *testing.T) {
+	tests := []struct {
+		failCnt    int
+		successCnt int
+	}{
+		{1, 1},
+		{5, 3},
+		{10, 10},
```
Comment (NingLin-P) [inline raft/raft_test.go]:
```suggestion
		{5, 10},
```
Test case of `failCnt ` > `successCnt `

File: raft/raft_test.go [hunk 4]
```diff
@@ -902,61 +869,55 @@ func TestDisruptiveFollower2AA(t *testing.T) {
...
+		nt.recover()
+		nt.send(pb.Message{From: 2, To: 2, MsgType: pb.MessageType_MsgBeat})
+		committed := sm1.RaftLog.nextEnts()
+		for _, log := range committed {
+			if log.Index == 1 {
+				continue
+			}
+			if log.Term != sm2.Term {
+				t.Fatalf("#%d: sm1 should commit entrie from sm2, got: %v", i, log)
 			}
```
Comment (NingLin-P) [inline raft/raft_test.go]:
```suggestion
		nt.recover()
		nt.ignore(pb.MessageType_MsgAppend)
		nt.send(pb.Message{From: 2, To: 2, MsgType: pb.MessageType_MsgBeat})
```
We should testing how`sm1`'s commit index update by `Heartbeat` instead of `AppendEntries`.

File: raft/raft_test.go [hunk 5]
```diff
@@ -902,61 +869,55 @@ func TestDisruptiveFollower2AA(t *testing.T) {
...
-			delete(wantCommitMap, m.To)
 		}
-		if len(m.Entries) != 0 {
-			t.Fatalf("#%d: len(entries) = %d, want 0", i, len(m.Entries))
+		if sm1.RaftLog.committed != wCommit {
```
Comment (NingLin-P) [inline raft/raft_test.go]:
```suggestion
		if sm1.RaftLog.committed == wCommit {
```

**Review by NingLin-P — APPROVED** [review]
LGTM, thanks!
